name: AdvancedCommandLogger
version: 1.0.0
main: com.aclogger.AdvancedCommandLogger
api-version: '1.21'
authors: [Krazy_kuro]

commands:
  aclogger:
    description: This plugin logs the commands player execute on the server

permissions:
  aclogger.reload:
    default: op
  aclogger.test:
    default: op
  aclogger.stats:
    default: op
  aclogger.bypass:
    default: false